![netflix_header](netflix_header.png)

# Netflix Top 10: Analyzing Weekly Chart-Toppers

This dataset comprises Netflix's weekly top 10 lists for the most-watched TV shows and films worldwide. The data spans from June 28, 2021, to August 27, 2023.

This workspace is pre-loaded with two CSV files. 
- `netflix_top10.csv` contains columns such as `show_title`, `category`, `weekly_rank`, and several view metrics.
- `netflix_top10_country.csv` has information about a show or film's performance by country, contained in the columns `cumulative_weeks_in_top_10` and `weekly_rank`.

We've added some guiding questions for analyzing this exciting dataset! Feel free to make this workspace yours by adding and removing cells, or editing any of the existing cells. 

[Source: Netflix](https://www.netflix.com/tudum/top10/united-states?week=2023-08-27)

## Explore this dataset

To get you started with your analysis...
1. Combine the different categories of top 10 lists in a single weekly top 10 list spanning all categories
2. Are there consistent trends or patterns in the content format (tv, film) that make it to the top 10 over different weeks or months?
3. Explore your country's top 10 trends. Are there unique preferences or regional factors that set your country's list apart from others?
4. Visualize popularity ranking over time through time series plots

### 🔍 **Scenario: Understanding the Impact of Content Duration on Netflix's Top 10 Lists**

This scenario helps you develop an end-to-end project for your portfolio.

Background: As a data scientist at Netflix, you're tasked with exploring the dataset containing weekly top 10 lists of the most-watched TV shows and films. For example, you're tasked to find out what the relationship is between duration and ranking over time. Answering this question can inform content creators and strategists on how to optimize their offerings for the platform.

**Objective**: Determine if there's a correlation between content duration and its likelihood of making it to the top 10 lists.

You can query the pre-loaded CSV files using SQL directly. Here’s a **sample query**:

In [4]:
SELECT show_title, MAX(cumulative_weeks_in_top_10) as max_cumulative_weeks_in_top_10
FROM 'netflix_top10_country.csv'
WHERE country_name = 'Argentina'
GROUP BY show_title
ORDER BY max_cumulative_weeks_in_top_10 DESC
LIMIT 3;

                show_title  max_cumulative_weeks_in_top_10
0      Pasión de Gavilanes                              82
1  Café con aroma de mujer                              31
2     Yo soy Betty, la fea                              31

In [5]:
import pandas as pd
global_top_10 = pd.read_csv("netflix_top10.csv", index_col=0)
print(global_top_10.shape)
global_top_10.head()

(4520, 10)

                   category  ...  episode_launch_details
week                         ...
2023-08-27  Films (English)  ...                     NaN
2023-08-27  Films (English)  ...                     NaN
2023-08-27  Films (English)  ...                     NaN
2023-08-27  Films (English)  ...                     NaN
2023-08-27  Films (English)  ...                     NaN

[5 rows x 10 columns]

In [6]:
countries_top_10 = pd.read_csv("netflix_top10_country.csv", index_col=0)
print(countries_top_10.shape)
countries_top_10.head()

(210880, 7)

             country_iso2        week  ... season_title  cumulative_weeks_in_top_10
country_name                           ...
Argentina              AR  2023-08-27  ...          NaN                           1
Argentina              AR  2023-08-27  ...          NaN                           2
Argentina              AR  2023-08-27  ...          NaN                           3
Argentina              AR  2023-08-27  ...          NaN                           1
Argentina              AR  2023-08-27  ...          NaN                           3

[5 rows x 7 columns]